apiVersion: v1
kind: Pod
spec:
  serviceAccount: 'jenkins'
  serviceAccountName: 'jenkins'
  containers:
  - name: helm
    image: alpine/helm
    command: ['cat']
    tty: true
    resources:
      limits: 
        memory: "786Mi"
        cpu: "600m"
      requests:
        memory: "456Mi"
        cpu: "300m"